title: DOTS Autonomous Space Robotic Platform
description: DOTS is the world`s first autonomous space robotic platform from NeuralSat.
show_downloads: false
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: dark
