title: DOTS Autonomous Space Robotic Platform
description: "DOTS is the world\'s first autonomous space robotic platform from NeuralSat."
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
